### ISSUE TITLE
Nonfloatable hidden window disappears on drop in empty area

### ISSUE THREAD

**Issue by boggi78** [githubuser0xFFFF/Qt-Advanced-Docking-System#496]
Hello,

thanks for your development, we really like to use it and test all of the possibilities. Unfortunately we experienced a little issue when using the autohide functionality.

**Version**
Qt 5.13.2
VisualStudio 2017 64 bit
Advanced Docking System 4.0.2

**Steps to reproduce**
1. Using demo app "AdvancedDockingSystemDemo"
2. Clicking "Pin Active Tab" on the "Filesystem 0 (c+ m+ f-)" (-> Window hides itself to buttom)
3. Clicking the hidden tab brings it to front
4. Click the title bar and move it somewhere into the application -> don't drop it into a valid docking container, but into an "empty area"

**Expected result**
Tab is NOT getting a floatable window (due to configuration) and pops back into the previous position (hidden tab).

**Actual result**
Window disappears.

Can you please help us out? 

Best regards,
Micha

https://user-images.githubusercontent.com/122113231/226462734-0375b238-a26e-4afb-9c49-0e13cb34577c.mp4

**Comment by githubuser0xFFFF** [comment]
Fixed this is master - please test. Do you have a link to the application in which you use ADS? I would like to add it to my showcase section. Maybe you have a screenshot or a link?

**Comment by boggi78** [comment]
Thank you for your fast response and bugfix.
The problem still persists.
i read your code and the added comment and i think my description was not exactly enough.
Following your comment i would add an additional case:
" Non floatable auto hide widgets should stay in its current auto hide
 state if they are dragged into a **invalid drop area**"
The main part here is the "invalid drop area"

Do you know what i mean?
I will ask somebody in our company for a permission  to make some screenshots for your showcase, because it is an internal tool.

**Comment by githubuser0xFFFF** [comment]
If I test here, I cannot see the issue from the video anymore. If I pin the "Filesystem 0 (c+ m+ f-)" window and try to drag it into a floating window, it stays in the auto hide state.

So I do not really understand the problem now. Please post a new video to show the problem.

**Comment by boggi78** [comment]
ok, sure
here a new recordered session

https://user-images.githubusercontent.com/122113231/226849315-2767201b-0c2a-4ac3-bca2-2a1b4cf66f13.mp4

**Comment by boggi78** [comment]
Ok.
Thank you!
