### ISSUE TITLE
Canceling an non-opaque dock drag

### ISSUE THREAD

**Issue by nickdademo** [githubuser0xFFFF/Qt-Advanced-Docking-System#90]
It would be nice to be able to cancel an in-progress opaque dock-drag by either pressing ESC or right-hand clicking the mouse.

**Comment by githubuser0xFFFF** [comment]
Do you mean non-opaque? Canceling an opaque docking is not possible, because the floating widget is created immediatelly. Only non-opaque docking can be canceled. I will implement this

**Comment by nickdademo** [comment]
Yes, sorry, I meant non-opaque.

**Comment by githubuser0xFFFF** [comment]
I just comitted some changes that makes it possible to cancel an non-opaque undock operation via escape key - please test it.

**Comment by nickdademo** [comment]
The cancelling via ESC key works - thanks!

Right-hand clicking while dragging is still a bit weird: the dock undocks but the `Detach` `Close` `Close Others` context menu pops up which doesn't make sense. Perhaps right-click could cancel the drag too?

An unrelated question: Do you think when you redock a floating dock to another area, it should become the active dock? Perhaps this could be a config setting? (currently, the active dock is preserved if another dock is added to the area)

**Comment by githubuser0xFFFF** [comment]
Fixed this now - right hand clicking should not show a context menu anymore.

Normally, if a floating widget is docket into a dock are it will become the active tab in the dock area.

**Comment by nickdademo** [comment]
> Fixed this now - right hand clicking should not show a context menu anymore.
> 
> Normally, if a floating widget is docket into a dock are it will become the active tab in the dock area.

Great! Tested and working on Windows. Thanks!

In regard to your 2nd point: when I dock a floating widget into an area, it does not become the active dock. Could this be a bug?

Also, `DragPreviewIsDynamic` feature doesn't seem to work on my end. The floating non-opaque dock does not resize at all - it just turns gray:

![image](https://user-images.githubusercontent.com/1648285/70960717-bfaccc00-20ba-11ea-967b-54d0f877bfc0.png)

**Comment by githubuser0xFFFF** [comment]
If I dock a floating widget into a dock area with several tabs, the docked widget becomes the active one.

Please test this with the demo application with Qt 5.12.2 and then test it with your Qt version.

If you use DragPreviewIsDynamic you should disable the flags `DragPreviewShowsContentPixmap` and `DragPreviewHasWindowFrame`. You should set the following flags:


```c++
    CDockManager::setConfigFlags(CDockManager::DefaultNonOpaqueConfig);
    CDockManager::setConfigFlag(CDockManager::DragPreviewShowsContentPixmap, false);
    CDockManager::setConfigFlag(CDockManager::DragPreviewIsDynamic, true);
```
This will paint a drag preview widget that looks like the overlay that is shown to indicate the drop target. As soon as a drop target is shown, the preview widget is hidden. This gives the impression, that the preview widget is dynamically adjusted to the size of the drop area.

While this looks nice, it do not think, that this is the best user experience. If the DragPreviewWidget is not dynamic, it is a better user experience.

**Comment by nickdademo** [comment]
Thanks for the explanation!

Your demo program behaves as expected (dropped widget becomes the active tab). So I'm not sure what is happening in my application...

**Comment by nickdademo** [comment]
> Thanks for the explanation!
> 
> Your demo program behaves as expected (dropped widget becomes the active tab). So I'm not sure what is happening in my application...

The culprit is  in ```DockContainerWidgetPrivate::moveIntoCenterOfSection```:

```TargetArea->insertDockWidget(0, DroppedDockWidget, false);``` where activate=false

So that is why the dropped dock is not becoming the active dock. How can I get it to activate in this case?

**Comment by githubuser0xFFFF** [comment]
This was a bug. I just fixed it.

**Comment by nickdademo** [comment]
Works! Thanks!

**Comment by nickdademo** [comment]
It looks like we have a regression on this. ESC no longer cancels the drag.

**Comment by githubuser0xFFFF** [comment]
Canceling works when dragging dock areas but not for dragging single dock widget tabs - i will fix this

**Comment by githubuser0xFFFF** [comment]
I just pushed a fix - it should work now.

**Comment by nickdademo** [comment]
This still seems broken both for single docks and dock areas (platform: Windows).

**Comment by githubuser0xFFFF** [comment]
I just fixed the problem in master

**Comment by nickdademo** [comment]
Hrmm, still no change. Let me triple-check that I'm building the latest code.

**Comment by githubuser0xFFFF** [comment]
Drag canceling only works for NonOpaque docking. Do you see the problem in the demo application or in your application? Would be great, if you could give me some more information when reporting bugs: Demo Application or Your Application? Linux, Windows, Mac?

I just tested the demo application and it works. So I guess it is in your application? Please try to change line 213 of `FloatingDragPreview.cpp`  from 

```c++
qApp->focusObject()->installEventFilter(this);
```
to

```c++
qApp->installEventFilter(this);
```

And tell me if it fixes the problem.

**Comment by nickdademo** [comment]
We are using: `CDockManager::eConfigFlag::OpaqueUndocking = false`

We are seeing this in our application.

The change you suggested works :) (for both dock groups and single docks)

**Comment by nickdademo** [comment]
Seems fixed in master, thanks!

**Comment by githubuser0xFFFF** [comment]
Thank you
